### ISSUE TITLE
Use of lowercase letters in the plug-in name

### ISSUE THREAD

**Issue by dtschump** [flathub/org.gimp.GIMP.Plugin.GMic#1]
Hello,
Thanks again for the Flatpak version of G'MIC.
I was wondering if there is any reason to have lowercase letters in the flatpak name (`GMic` instead of `GMIC`).
G'MIC being an acronym, it is composed of only uppercase letters.

Also `> flatpack search gmic` shows an incorrect description:
~~~~
$ flatpak search gmic
Name                              Description                          Application ID              Version   Branch   Remotes
G'Mic                             GREYC's Magic Image For Computing    org.gimp.GIMP.Plugin.GMic   2.9.1     2-3.36   flathub
~~~~
There is a mistake in the description string, the correct sentence should be `GREYC's Magic For Image Computing` (the `For` has been incorrectly shifted to the right).

Thanks!

**Comment by hfiguiere** [comment]
merged
