### ISSUE TITLE
GIMP Flatpak plugin doesn't work? Installs but nothing added to GIMP's Filter menu.

### ISSUE THREAD

**Issue by JaneSmith** [flathub/org.gimp.GIMP.Plugin.GMic#21]
I've installed the Flatpak plugin via the instructions on the G'Mic website:

```
flatpak install flathub org.gimp.GIMP.Plugin.GMic
```

When I do this, Flatpak informs me that there are two different versions available:

```
Looking for matches…
Similar refs found for ‘org.gimp.GIMP.Plugin.GMic’ in remote ‘flathub’ (system):

   1) runtime/org.gimp.GIMP.Plugin.GMic/x86_64/2-40
   2) runtime/org.gimp.GIMP.Plugin.GMic/x86_64/2-3.36

Which do you want to use (0 to abort)? [0-2]:
```

The instructions on the website don't say what to do here, but regardless I tried both one at a time.

Regardless of which one I install, when I re-open GIMP there's no G'Mic option in the Filters menu. Am I doing something wrong?

**Comment by hfiguiere** [comment]
select the first one.

**Comment by JaneSmith** [comment]
Thanks for clarifying that. I'll use the first one then. But as I said, I already tried both of them, and neither of them are working.

I tried deleting my `~/.var/app/org.gimp.GIMP/config/GIMP/2.10/pluginrc` file to force GIMP to re-scan plugins, but that didn't help anything either. I've tried running GIMP via the terminal and there are no errors that I can see.

**Comment by hfiguiere** [comment]
are you sure you run GIMP 2.10 from flathub and not any other version?

**Comment by JaneSmith** [comment]
That was the problem. I've accidentally been using GIMP from Fedora's Flatpak repository instead of Flathub. I always want to be using Flathub, but I guess somehow the Fedora Flatpak repository was selected in GNOME Software when I installed GIMP. I should really just remove that repository entirely to avoid accidents...

After reinstalling GIMP from the proper Flathub repo all is working as it should.

I'm very sorry for wasting your time! Please accept my apologies. Thanks a lot for your help.

**Comment by hfiguiere** [comment]
Note: I'm working on a solution so that only one plugin appear when you look for it.
